# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-flux-system-webhooks
  namespace: flux-system
spec:
  dependsOn:
  - name: core-kube-system-cilium
  path: ./kubernetes/deployments/core/flux-system/addons/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
