# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflared-secret
  namespace: networking
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "cloudflare tunnel"
      property: credentials.json
  data:
  - secretKey: TUNNEL_ID
    remoteRef:
      key: "Cloudflare"
      property: "tunnel id"
