# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: grafana-admin-secret
  namespace: monitoring
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: admin-password
    remoteRef:
      key: "Grafana"
      property: password
  - secretKey: admin-user
    remoteRef:
      key: "Grafana"
      property: username
