# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
- ./grafana-admin-external-secret.yaml
- ./cloudflare-application.yaml
- ./helmrelease.yaml
