apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-k8s-gateway
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-core-nginx-external
  path: ./kubernetes/deployments/core/networking/k8s-gateway/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
