apiVersion: v2
name: nextcloud
description: A Helm chart for Kubernetes
type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
- name: nextcloud
  version: ~2.12.1
  repository: https://nextcloud.github.io/helm/