# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
  namespace: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        INIT_POSTGRES_DBNAME: authentik
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .AUTHENTIK_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .AUTHENTIK_POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        REDIS_HOST: redis.database.svc.cluster.local
  dataFrom:
  - extract:
      key: cloudnative-pg
  - extract:
      key: authentik
