# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.2.1
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    initContainers:
      01-init-db:
        image: ghcr.io/kflix-tv/postgres-init:16.2@sha256:a0362cce769f35777e3792a9fa74180965f7f1d9b4bc8035552853f6d3e076c7
        imagePullPolicy: IfNotPresent
        envFrom: &envFrom
        - secretRef:
            name: authentik-secret
            # TODO: GeoIP container
    replicas: 2
    authentik:
      error_reporting:
        enabled: false
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/ssl-redirect: "true"
      hosts:
      - host: &host authentik.${SECRET_DOMAIN}
        paths:
        - path: "/"
          pathType: Prefix
      tls:
      - hosts:
        - *host
    prometheus:
      serviceMonitor:
        enabled: true
      rules:
        create: true
    geoip:
      enabled: false #TODO: Enable GeoIP

  valuesFrom:
  - kind: Secret
    name: authentik-secret
    valuesKey: AUTHENTIK_SECRET_KEY
    targetPath: authentik.secret_key
  - kind: Secret
    name: authentik-secret
    valuesKey: INIT_POSTGRES_DBNAME
    targetPath: authentik.postgresql.name
  - kind: Secret
    name: authentik-secret
    valuesKey: INIT_POSTGRES_HOST
    targetPath: authentik.postgresql.host
  - kind: Secret
    name: authentik-secret
    valuesKey: INIT_POSTGRES_USER
    targetPath: authentik.postgresql.user
  - kind: Secret
    name: authentik-secret
    valuesKey: INIT_POSTGRES_PASS
    targetPath: authentik.postgresql.password
  - kind: Secret
    name: authentik-secret
    valuesKey: REDIS_HOST
    targetPath: authentik.redis.host
