plex:
  env:
    TZ: america/los_angeles
    PLEX_CLAIM: claim-msqoMV-DjroHM272CwmN
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: plex.kflix.tv
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - plex.kflix.tv
  persistence:
    config:
      storageClass: "longhorn-kflix"
  # extraVolumeMounts:
  #   - name: tv
  #     mountPath: /mnt/disks/tv
  #     mountPropagation: Bidirectional
  # extraVolumes:
  #   - name: tv
  #     hostPath:
  #       path: /mnt/disks/tv
  