plex:
  env:
    TZ: america/los_angeles
    PLEX_CLAIM: claim-cAZ2S_xBjAxvyYfRfr56
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: plex.kflix.tv
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: plex-tls
      hosts:
      - plex.kflix.tv
  persistence:
    config:
      storageClass: "longhorn-kflix"
  extraVolumeMounts:
    - name: tv
      mountPath: /mnt/disks/tv
      mountPropagation: HostToContainer
  extraVolumes:
    - name: tv
      hostPath:
        path: /mnt/disks/tv
  livenessProbe:
    exec:
      command:
      - cat
      - /mnt/disks/tv/.test
    initialDelaySeconds: 5
    periodSeconds: 5
kube-rclone:
  images:
    initContainer:
      repository: busybox
      tag: latest
    container:
      repository: ghcr.io/kflix-tv/rclone
      tag: v1
    pullPolicy: IfNotPresent

  rclone:
    #  remote to mount from rclone config
    remote: "movies-crypt:"
    # mount path for  remote
    path: /mnt/disks/movies
    # read only file system for remote (to protect from deletion of files)
    readOnly: true
    # additional arguments for customising rclone
    # mount options can be found here - https://rclone.org/commands/rclone_mount/#options
    additionalArgs:
      # - --buffer-size=1G
      # - --dir-cache-time=72h
      # - --drive-chunk-size=256M
      # - --fast-list
      # - --log-level=INFO
      # - --vfs-read-chunk-size=128M
      # - --vfs-read-chunk-size-limit=off
      # - --drive-acknowledge-abuse=true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # requests:
    #   cpu: 250m
    #   memory: 1Gi
    # limits:
    #   cpu: 350m
    #   memory: 2Gi

  nodeSelector: {}