plex:
  env:
    TZ: america/los_angeles
    PLEX_CLAIM: claim-cAZ2S_xBjAxvyYfRfr56
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: plex.kflix.tv
      paths:
      - path: /
        pathType: Prefix
    tls:
    - secretName: plex-tls
      hosts:
      - plex.kflix.tv
  persistence:
    existingClaim: plex-longhorn-pvc
  extraVolumeMounts:
    - name: tv
      mountPath: /mnt/disks/tv
      mountPropagation: HostToContainer
    - name: movies
      mountPath: /mnt/disks/movies
      mountPropagation: HostToContainer
  extraVolumes:
    - name: tv
      hostPath:
        path: /mnt/disks/tv
    - name: movies
      hostPath:
        path: /mnt/disks/movies
  livenessProbe:
    exec:
      command:
      - cat
      - /mnt/disks/tv/.test
    initialDelaySeconds: 5
    periodSeconds: 5

rclone-tv:
  config: |
    [gdrive]
    type = drive
    client_id = 447142735064-3avhbvpvqrvftcojq01m6gruds5v728c.apps.googleusercontent.com
    client_secret = kYGwU8acgJ7DpHJT54jXczp0
    token = {"access_token":"ya29.A0ARrdaM_Hg-1bj0tGt5lgZGZvXs2_kHavXSADBxubzVpJnJjh6yS4TOhyW1vELLlWMCxhFplKhffMXyg6uOyCA1tRgOMPQXEB8IJ7Gke1Z7KeyW7qTVpRjdaX-YZXWURkotswV30x-xAxQN33EklzPX94pjCr4U4","token_type":"Bearer","refresh_token":"1/32CUwKt-z2N8CKBQAMswhZYomWAQyy5dk9mhY3jWhAE","expiry":"2022-03-01T16:26:51.219908087-08:00"}

    [tv-crypt]
    type = crypt
    remote = gdrive:/etijrp2eg47fm2n1h9taivo8rc/sekan4rpgsf9t7h1itsmn51vc4
    filename_encryption = standard
    password = WxrfeV7cq72ymLVJSFZTxLGwoDRrEJLi-BOSbTk6FrE6Wkqn7826pZGTOl8zJUG_IjXnl1dKYPhBLwg
    password2 = ZIYdqZFdHC-JfvmhaKCnnUf5RGv3XxgwZ80PP7OhMCKxRWPdoNLHtjtK4QTsgRi5cwPh2aea5b8ILqA
  images:
    initContainer:
      repository: busybox
      tag: latest
    container:
      repository: ghcr.io/kflix-tv/rclone
      tag: v1
    pullPolicy: IfNotPresent

  rclone:
    #  remote to mount from rclone config
    remote: "tv-crypt:"
    # mount path for  remote
    path: /mnt/disks/tv
    # read only file system for remote (to protect from deletion of files)
    readOnly: true
    # additional arguments for customising rclone
    # mount options can be found here - https://rclone.org/commands/rclone_mount/#options
    additionalArgs: 
      # - --buffer-size=1G
      # - --dir-cache-time=72h
      # - --drive-chunk-size=256M
      # - --fast-list
      # - --log-level=INFO
      # - --vfs-read-chunk-size=128M
      # - --vfs-read-chunk-size-limit=off
      # - --drive-acknowledge-abuse=true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # requests:
    #   cpu: 250m
    #   memory: 1Gi
    # limits:
    #   cpu: 350m
    #   memory: 2Gi

  nodeSelector: {}

rclone-movies:
  config: |
    [gdrive]
    type = drive
    client_id = 447142735064-3avhbvpvqrvftcojq01m6gruds5v728c.apps.googleusercontent.com
    client_secret = kYGwU8acgJ7DpHJT54jXczp0
    token = {"access_token":"ya29.A0ARrdaM_Hg-1bj0tGt5lgZGZvXs2_kHavXSADBxubzVpJnJjh6yS4TOhyW1vELLlWMCxhFplKhffMXyg6uOyCA1tRgOMPQXEB8IJ7Gke1Z7KeyW7qTVpRjdaX-YZXWURkotswV30x-xAxQN33EklzPX94pjCr4U4","token_type":"Bearer","refresh_token":"1/32CUwKt-z2N8CKBQAMswhZYomWAQyy5dk9mhY3jWhAE","expiry":"2022-03-01T16:26:51.219908087-08:00"}

    [movies-crypt]
    type = crypt
    remote = gdrive:/etijrp2eg47fm2n1h9taivo8rc/hb8acqmosapn02o7qnsq76jmvs
    filename_encryption = standard
    password = WxrfeV7cq72ymLVJSFZTxLGwoDRrEJLi-BOSbTk6FrE6Wkqn7826pZGTOl8zJUG_IjXnl1dKYPhBLwg
    password2 = ZIYdqZFdHC-JfvmhaKCnnUf5RGv3XxgwZ80PP7OhMCKxRWPdoNLHtjtK4QTsgRi5cwPh2aea5b8ILqA
  images:
    initContainer:
      repository: busybox
      tag: latest
    container:
      repository: ghcr.io/kflix-tv/rclone
      tag: v1
    pullPolicy: IfNotPresent

  rclone:
    #  remote to mount from rclone config
    remote: "movies-crypt:"
    # mount path for  remote
    path: /mnt/disks/movies
    # read only file system for remote (to protect from deletion of files)
    readOnly: true
    # additional arguments for customising rclone
    # mount options can be found here - https://rclone.org/commands/rclone_mount/#options
    additionalArgs: 
      # - --buffer-size=1G
      # - --dir-cache-time=72h
      # - --drive-chunk-size=256M
      # - --fast-list
      # - --log-level=INFO
      # - --vfs-read-chunk-size=128M
      # - --vfs-read-chunk-size-limit=off
      # - --drive-acknowledge-abuse=true

  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # requests:
    #   cpu: 250m
    #   memory: 1Gi
    # limits:
    #   cpu: 350m
    #   memory: 2Gi

  nodeSelector: {}