plex:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
    - host: plex.kflix.tv
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - plex.kflix.tv
