# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-credentials
  namespace: external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: ghcr-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      engineVersion: v2
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "ghcr.io": {
                "username": "{{ .GITHUB_USERNAME }}",
                "password": "{{ .credential }}",
                "email": "{{ .username }}",
                "auth": "{{ list .GITHUB_USERNAME .credential | join ":" | b64enc }}"
              }
            }
          }
  dataFrom:
  - extract:
      key: "Github - Flux"
