# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/cloudflare.zelic.io/cloudflareaccessapplication_v1alpha1.json
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: prometheus
  namespace: monitoring
spec:
  name: Prometheus
  domain: "prometheus.${SECRET_DOMAIN}"
  autoRedirectToIdentity: true
  policies:
  - name: Allow admin
    decision: allow
    include:
    - accessGroups:
      - valueFrom:
          name: adminonly
          namespace: zero-trust
---
# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/cloudflare.zelic.io/cloudflareaccessapplication_v1alpha1.json
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  name: Alert Manager
  domain: "alertmanager.${SECRET_DOMAIN}"
  autoRedirectToIdentity: true
  policies:
  - name: Allow admin
    decision: allow
    include:
    - accessGroups:
      - valueFrom:
          name: adminonly
          namespace: zero-trust
