apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-gatus-ep
  namespace: monitoring
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Prometheus
        group: Admin
        url: https://prometheus.kflix.tv/-/healthy
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
