# yaml-language-server builtin
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
