# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storage-configuration
  namespace: minio-tenant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: storage-configuration
    template:
      engineVersion: v2
      data:
        config.env: |
          export MINIO_ROOT_USER="{{.MINIO_ROOT_USER}}"
          export MINIO_ROOT_PASSWORD="{{.MINIO_ROOT_PASSWORD}}"
          export MINIO_STORAGE_CLASS_STANDARD="EC:2"
          export MINIO_BROWSER="on"
  dataFrom:
  - extract:
      key: "minio"
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: storage-user
  namespace: minio-tenant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: storage-user
    template:
      engineVersion: v2
      data:
        CONSOLE_ACCESS_KEY: "{{.CONSOLE_ACCESS_KEY}}"
        CONSOLE_SECRET_KEY: "{{.CONSOLE_SECRET_KEY}}"
  dataFrom:
  - extract:
      key: "minio"
