changelog:
  exclude:
    labels:
    - type/digest
  categories:
  - title: Breaking Changes 🛠
    labels:
    - type/major
  - title: Exciting New Features 🎉
    labels:
    - type/minor
  - title: Other Changes
    labels:
    - "*"
