fail_fast: false
repos:
- repo: https://github.com/gruntwork-io/pre-commit
  rev: v0.1.22
  hooks:
  - id: terraform-fmt
- repo: https://github.com/compilerla/conventional-pre-commit
  rev: v2.4.0
  hooks:
  - id: conventional-pre-commit
    stages: [commit-msg]
    args: []
# - repo: https://github.com/ansible-community/ansible-lint
#   rev: v6.20.3
#   hooks:
#   - id: ansible-lint
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.32.0
  hooks:
  - id: yamllint
    args: [--strict, -c=.yamllint]
