version: "3"

vars:
  PYTHON_BIN: python3
  PROJECT_DIR:
    sh: "git rev-parse --show-toplevel"
  KUBERNETES_DIR: "{{.PROJECT_DIR}}/kubernetes"
  ANSIBLE_DIR: "{{.PROJECT_DIR}}/ansible"
  TERRAFORM_DIR: "{{.PROJECT_DIR}}/terraform"

dotenv: [".config.env"]

env:
  KUBECONFIG: "{{.HOME}}/.kube/config-files/kflix.yaml"
  PATH: "{{.ROOT_DIR}}/.venv/bin:$PATH"
  VIRTUAL_ENV: "{{.ROOT_DIR}}/.venv"
  ANSIBLE_COLLECTIONS_PATH: "{{.ROOT_DIR}}/.venv/galaxy"
  ANSIBLE_ROLES_PATH: "{{.ROOT_DIR}}/.venv/galaxy/ansible_roles"
  ANSIBLE_VARS_ENABLED: "host_group_vars,community.sops.sops"

includes:
  ansible: .taskfiles/AnsibleTasks.yml
  cloudflare: .taskfiles/CloudflareTasks.yml
  cluster: .taskfiles/KubernetesTasks.yml
  flux: .taskfiles/KubernetesTasks.yml
  github: .taskfiles/GithubTasks.yml
  kubernetes: .taskfiles/KubernetesTasks.yml
  precommit: .taskfiles/PrecommitTasks.yml
  terraform: .taskfiles/TerraformTasks.yml

tasks:

  init:
    desc: Initialize workstation dependencies with Brew
    cmds:
    - brew install {{.DEPS}} {{.CLI_ARGS}}
    preconditions:
    - sh: command -v brew
      msg: |
        Homebrew is not installed. Using MacOS, Linux or WSL?
        Head over to https://brew.sh to get up and running.
    vars:
      DEPS: age ansible argocd direnv fluxcd/tap/flux gh helm ipcalc jq kubernetes-cli kustomize pre-commit prettier sops stern terraform tflint weaveworks/tap/gitops yamllint yq

  terraform:
    desc: Alias to `terraform:deploy`
    cmds:
    - task: terraform:deploy

  ansible:
    desc: Alias to `ansible:deploy`
    cmds:
    - task: ansible:deploy

  kubernetes:
    desc: Alias to `kubernetes:deploy`
    cmds:
    - task: kubernetes:deploy

  full-install:
    desc: This will call all tasks in order to fully setup a cluster with "One-Click"
    cmds:
    - task: init
    - task: terraform
    - task: ansible
    - task: kubernetes

  redeploy:
    desc: Runs an `ansible:reinstall` followed by a `kubernetes:deploy`
    cmds:
    - task: ansible:reinstall
    - task: kubernetes:deploy
