# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minio
  namespace: datastore
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: minio-secret
    creationPolicy: Owner
  dataFrom:
  - extract:
      # MINIO_ROOT_USER, MINIO_ROOT_PASSWORD, MINIO_PROMETHEUS_TOKEN
      key: minio
