# yaml-language-server builtin
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: datastore
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn-kflix
  resources:
    requests:
      storage: 40Gi
