# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-minio-operator-minio-operator
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/core/minio-operator/minio-operator/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  interval: 30m
  retryInterval: 1m
  timeout: 5m
