apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cloudflare-zerotrust-secret
  namespace: zero-trust
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: CLOUDFLARE_ACCOUNT_ID
    remoteRef:
      key: "Cloudflare"
      property: "account id"
  - secretKey: CLOUDFLARE_API_TOKEN
    remoteRef:
      key: "Cloudflare"
      property: "zerotrust"
  - secretKey: CLOUDFLARE_API_EMAIL
    remoteRef:
      key: "Cloudflare"
      property: "username"
  - secretKey: CLOUDFLARE_API_KEY
    remoteRef:
      key: "Cloudflare"
      property: ""
