# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cloudflare-zerotrust
  namespace: zero-trust
spec:
  interval: 30m
  chart:
    spec:
      chart: cloudflare-zero-trust-operator
      version: 0.3.1
      sourceRef:
        kind: HelmRepository
        name: zelic-io
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    secretRef: cloudflare-zerotrust-secret
