---
apiVersion: v1
kind: Secret
metadata:
  name: focal
  namespace: system-upgrade
type: Opaque
stringData:
  upgrade.sh: |
    #!/bin/sh
    set -e
    secrets=$(dirname $0)
    apt-get --assume-yes update
    apt-get --assume-yes upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: focal
  namespace: system-upgrade
spec:
  concurrency: 2
  nodeSelector:
    matchExpressions:
      - {key: plan.upgrade.cattle.io/focal, operator: Exists}
  serviceAccountName: system-upgrade
  secrets:
    - name: focal
      path: /host/run/system-upgrade/secrets/focal
  drain:
    force: true
  version: focal
  upgrade:
    image: ubuntu
    command: ["chroot", "/host"]
    args: ["sh", "/run/system-upgrade/secrets/focal/upgrade.sh"]