# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: actions-runner-controller-auth
  namespace: actions-runner-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: actions-runner-controller-auth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        github_app_id: "{{ .github_app_id }}"
        github_app_installation_id: "{{ .github_app_installation_id }}"
        github_app_private_key: "{{ .github_app_private_key | b64dec  }}"

  dataFrom:
  - extract:
      # github_app_id, github_app_installation_id, github_app_private_key
      key: actions-runner-controller
