# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: csi-rclone
  namespace: flux-system
spec:
  interval: 1h
  url: https://kflix-tv.github.io/helm-csi-rclone
