# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: kflix-tv
  namespace: flux-system
spec:
  type: oci
  interval: 5m
  url: oci://ghcr.io/kflix-tv/helm
