# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./bitnami.yaml
- ./bjw-s.yaml
- ./cilium.yaml
- ./cloudnative-pg.yaml
- ./clustersecret.yaml
- ./coredns.yaml
- ./csi-rclone.yaml
- ./external-dns.yaml
- ./external-secrets.yaml
- ./grafana.yaml
- ./hajimari.yaml
- ./ingress-nginx.yaml
- ./jetstack.yaml
- ./k8s-gateway.yaml
- ./kubernetes-dashboard.yaml
- ./kyverno.yaml
- ./longhorn.yaml
- ./metrics-server.yaml
- ./minio.yaml
- ./onepassword.yaml
- ./piraeus.yaml
- ./prometheus-community.yaml
- ./rook-ceph.yaml
- ./stakater.yaml
- ./weave-gitops.yaml
- ./zelic-io.yaml
