apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./bitnami.yaml
- ./bjw-s.yaml
- ./cilium.yaml
- ./coredns.yaml
- ./external-dns.yaml
- ./external-secrets.yaml
- ./grafana.yaml
- ./hajimari.yaml
- ./ingress-nginx.yaml
- ./jetstack.yaml
- ./k8s-gateway.yaml
- ./kubernetes-dashboard.yaml
- ./longhorn.yaml
- ./metrics-server.yaml
- ./onepassword.yaml
- ./prometheus-community.yaml
- ./stakater.yaml
- ./weave-gitops.yaml
- ./zelic-io.yaml
