# yaml-language-server builtin
apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-gatus-ep
  namespace: observability
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: loki
        group: Guarded
        url: 1.1.1.1
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: loki.${SECRET_DOMAIN}
          query-type: A
        conditions:
          - "len([BODY]) == 0"
