# yaml-language-server: $schema=https://k8s-schemas.pages.dev/longhorn.io/recurringjob_v1beta2.json
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-backup
  namespace: longhorn-system
spec:
  name: daily-backup
  concurrency: 1
  cron: '* * * * ?'
  groups:
  - default
  retain: 3
  task: backup
