# yaml-language-server: $schema=https://k8s-schemas.pages.dev/cloudflare.zelic.io/cloudflareaccessapplication_v1alpha1.json
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: thanos
  namespace: observability
spec:
  name: Thanos
  domain: "thanos-query-frontend.${SECRET_DOMAIN}"
  autoRedirectToIdentity: true
  policies:
  - name: Allow admin
    decision: allow
    include:
    - accessGroups:
      - valueFrom:
          name: adminonly
          namespace: zero-trust
