# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: startup-clustersecret-clustersecret
  namespace: flux-system
spec:
  dependsOn:
  - name: startup-external-secrets-cluster-secrets
  path: ./kubernetes/deployments/startup/clustersecret/clustersecret/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: startup-clustersecret-secrets-replication
  namespace: flux-system
spec:
  dependsOn:
  - name: startup-clustersecret
  path: ./kubernetes/deployments/startup/clustersecret/clustersecret/secrets-replication
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
