# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-github-runner
  namespace: actions-runner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.7.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-github-runner
    githubConfigSecret: actions-runner-controller-auth-secret
    githubConfigUrl: https://github.com/kflix-tv/k8s-kflix
    minRunners: 1
    maxRunners: 6
    containerMode:
      type: dind
    template:
      spec:
        containers:
        - name: runner
          image: ghcr.io/actions-runner-controller/actions-runner-controller/actions-runner-dind:v2.311.0-ubuntu-20.04-8e48463
          imagePullPolicy: IfNotPresent
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
