# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runner-set-kflix
  namespace: actions-runner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.3
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-runner-set-kflix
    githubConfigSecret: actions-runner-controller-auth-secret
    githubConfigUrl: https://github.com/kflix-tv
    minRunners: 2
    maxRunners: 12
    containerMode:
      type: dind
    template:
      spec:
        containers:
        - name: runner
          image: ghcr.io/kflix-tv/actions-runner:2.313.0@sha256:609bc18a20123b1fc1d9dc2018828428666ad0a5caa9db45fee4ba8eacafb62f
          command: ["/home/runner/run.sh"]
          imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: ghcr-credentials
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
