# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/helm.toolkit.fluxcd.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: arc-runner-set-kflix
  namespace: actions-runner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    runnerScaleSetName: arc-runner-set-kflix
    githubConfigSecret: actions-runner-controller-auth-secret
    githubConfigUrl: https://github.com/kflix-tv/k8s-kflix
    minRunners: 2
    maxRunners: 12
    containerMode:
      type: dind
    template:
      spec:
        containers:
        - name: runner
          image: ghcr.io/kflix-tv/github-actions-runner:rolling@sha256:9c46bfe14bc5119476f4852e45e7546bed585b8f65cc1b44140cfd637e3757d2
          imagePullPolicy: IfNotPresent
        imagePullSecrets:
        - name: ghcr-credentials
    controllerServiceAccount:
      name: actions-runner-controller-gha-rs-controller
      namespace: actions-runner-system
