# yaml-language-server: $schema=https://k8s-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-staging"
  namespace: network
spec:
  secretName: "${SECRET_DOMAIN/./-}-staging-tls"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
  - "${SECRET_DOMAIN}"
  - "*.${SECRET_DOMAIN}"
# ---
# # yaml-language-server: $schema=https://k8s-schemas.pages.dev/cert-manager.io/certificate_v1.json
# apiVersion: cert-manager.io/v1
# kind: Certificate
# metadata:
#   name: "${HOME_DOMAIN/./-}-staging"
#   namespace: network
# spec:
#   secretName: "${HOME_DOMAIN/./-}-staging-tls"
#   issuerRef:
#     name: letsencrypt-staging
#     kind: ClusterIssuer
#   commonName: "${HOME_DOMAIN}"
#   dnsNames:
#   - "${HOME_DOMAIN}"
#   - "*.${HOME_DOMAIN}"
