oauth2-proxy:
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: letsencrypt
    hosts:
      - oauth2.kflix.tv
    tls:
      - secretName: oauth2-tls
        hosts:
          - oauth2.kflix.tv