# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-network-cloudflared
  namespace: flux-system
spec:
  dependsOn:
  - name: core-network-external-dns
  path: ./kubernetes/deployments/core/network/cloudflared/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  interval: 30m
  retryInterval: 1m
  timeout: 5m
