apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: op-secret-store
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect
      vaults:
        kubernetes: 1 # look in this vault first
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
