kubernetes:
  vars:
    ansible_user: ubuntu
    ansible_ssh_port: 22
  children:
    master:
      hosts:
        kflix:
          ansible_host: 51.222.43.228
    workers:
      hosts:
        kflix:
          ansible_host: 51.222.43.228
