# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argo-cd
#   namespace: {{ .Values.metadata.namespace }}
# spec:
#   project: default

#   source:
#     repoURL: {{ .Values.spec.source.repoURL }}
#     targetRevision: HEAD
#     path: helm-charts/argo-cd
#   destination: 
#     server: {{ .Values.spec.destination.server }}
#     namespace: argo-cd

#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true

#     automated:
#       selfHeal: true
#       prune: true