apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: {{ .Values.spec.project }}

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: helm-charts/external-secrets
  destination: 
    server: {{ .Values.spec.destination.server }}
    namespace: external-secrets

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true