apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: {{ .Values.metadata.namespace }}
spec:
  project: {{ .Values.spec.project }}

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: helm-charts/external-dns
  destination: 
    server: {{ .Values.spec.destination.server }}
    namespace: external-dns

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true