# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: hello-kubernetes
#   namespace: {{ .Values.metadata.namespace }}
# spec:
#   project: default

#   source:
#     repoURL: {{ .Values.spec.source.repoURL }}
#     targetRevision: HEAD
#     path: 'hello-kubernetes'
#   destination: 
#     server: {{ .Values.spec.destination.server }}
#     namespace: hello-kubernetes

#   syncPolicy:
#     syncOptions:
#     - CreateNamespace=true

#     automated:
#       selfHeal: true
#       prune: true