apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: {{ .Values.spec.project }}

  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
    path: helm-charts/longhorn
  destination: 
    server: {{ .Values.spec.destination.server }}
    namespace: longhorn-system

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true