apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-core-cloudflare-zerotrust-access-group
  path: ./kubernetes/deployments/core/monitoring/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
