apiVersion: v1
kind: Secret
metadata:
  name: flux-github-secret
  namespace: flux-system
type: Opaque
stringData:
  username: "op://Kubernetes/Github - Flux/username"
  password: "op://Kubernetes/Github - Flux/credential"
