apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: onepassword-connect-token
  namespace: external-secrets
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
type: Opaque
stringData:
  token: "op://Kubernetes/external-secrets/password"
