# yaml-language-server builtin
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: observability
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: ceph-filesystem
  resources:
    requests:
      storage: 2Gi
