apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.5.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    # https://artifacthub.io/packages/helm/longhorn/longhorn?modal=values
    namespaceOverride: "longhorn-system"
    ingress:
      enabled: true
      ingressClassName: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hajimari.io/group: "Admin Only"
        hajimari.io/icon: "harddrive"
        hajimari.io/appName: "Longhorn"
      tls: true
      host: "longhorn.${SECRET_DOMAIN}"
    defaultSettings:
      defaultDataPath: "/mnt/data/longhorn"
