apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: SECRET_ACME_EMAIL
    remoteRef:
      key: "Letsencrypt"
      property: username
  - secretKey: SECRET_DOMAIN
    remoteRef:
      key: "Cloudflare"
      property: domain
