# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: SECRET_ACME_EMAIL
    remoteRef:
      key: "Letsencrypt"
      property: username
  - secretKey: SECRET_DOMAIN
    remoteRef:
      key: "Cloudflare"
      property: domain
  - secretKey: SECRET_CLOUDFLARE_TUNNEL_ID
    remoteRef:
      key: "Cloudflare"
      property: "tunnel id"
  - secretKey: HOME_DOMAIN
    remoteRef:
      key: "Cloudflare"
      property: "home_domain"
