# TODO: Create yaml-language-server schema for this file
apiVersion: cloudflare.zelic.io/v1alpha1
kind: CloudflareAccessApplication
metadata:
  name: weave-gitops
  namespace: monitoring
spec:
  name: weave-gitops
  domain: "gitops.${SECRET_DOMAIN}"
  autoRedirectToIdentity: true
  policies:
  - name: Allow admin
    decision: allow
    include:
    - accessGroups:
      - valueFrom:
          name: adminonly
          namespace: zero-trust
