# yaml-language-server builtin
apiVersion: v1
kind: ConfigMap
metadata:
  name: weave-gitops-gatus-ep
  namespace: flux-system
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: Weave GitOps
        group: Admin
        url: https://gitops.kflix.tv/health/
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
