apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: cluster-user-auth
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: "Weave"
      property: password
  - secretKey: username
    remoteRef:
      key: "Weave"
      property: username
