# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: flux-system
resources:
- ./gitops-external-secret.yaml
- ./helmrelease.yaml
- ./cloudflare-application.yaml
