# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kube-system-metrics-server
  namespace: flux-system
spec:
  dependsOn:
  - name: core-networking-external-dns
  path: ./kubernetes/deployments/core/kube-system/metrics-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
