apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: onepassword-connect
  namespace: op
spec:
  interval: 30m
  chart:
    spec:
      chart: connect
      version: 1.13.0
      sourceRef:
        kind: HelmRepository
        name: onepassword
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
