apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: csi-rclone
  namespace: csi-rclone
spec:
  interval: 30m
  chart:
    spec:
      chart: csi-rclone
      version: 2023.9.2
      sourceRef:
        kind: HelmRepository
        name: csi-rclone
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # values:
