apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-external-dns
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/core/networking/external-dns/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
