kube-prometheus-stack:
  alertmanager:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - alertmanager.kflix.tv
      paths:
      - /
      tls:
      - secretName: alertmanager-tls
        hosts:
        - alertmanager.kflix.tv
  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - grafana.kflix.tv
      paths:
      - /
      tls:
      - secretName: grafana-tls
        hosts:
        - grafana.kflix.tv
  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - prometheus.kflix.tv
      paths:
      - /
      tls:
      - secretName: prometheus-tls
        hosts:
        - prometheus.kflix.tv