apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-cloudflared
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-core-external-dns
  path: ./kubernetes/deployments/core/networking/cloudflared/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
