apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
      annotations:
        diun.enable: "true"
    spec:
      serviceAccountName: {{ .Values.name }}
      containers:
        - name: {{ .Values.name }}
          image: crazymax/diun:latest
          imagePullPolicy: Always
          args: ["serve"]
          env:
            - name: TZ
              value: "America/Los_Angeles"
            - name: LOG_LEVEL
              value: "info"
            - name: DIUN_NOTIF_PUSHOVER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: pushover-api-token
                  key: account_token
            - name: DIUN_NOTIF_PUSHOVER_RECIPIENT
              valueFrom:
                  secretKeyRef:
                    name: pushover-api-token
                    key: user
          volumeMounts:
            - mountPath: "/etc/diun/diun.yaml"
              name: diun-config
              subPath: diun.yaml
      restartPolicy: Always
      volumes:
        - name: diun-config
          configMap:
            name: diun-config
            items:
              - key: diun.yaml
                path: diun.yaml