# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-network-nginx-certificates
  namespace: flux-system
spec:
  dependsOn:
  - name: core-cert-manager-issuers
  - name: core-zero-trust-cloudflare-zerotrust
  path: ./kubernetes/deployments/core/network/nginx/certificates
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-network-nginx-external
  namespace: flux-system
spec:
  dependsOn:
  - name: core-network-nginx-certificates
  path: ./kubernetes/deployments/core/network/nginx/external
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m

# TODO: Enable "Internal only" nginx for Cloudflare Access
# This can probably use Kustomize's "patches" feature to add the annotations
# as well as the cloudflare application piece

# ---
# # yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: core-nginx-internal
#   namespace: flux-system
# spec:
#   dependsOn:
#   - name: core-nginx-certificates
#   path: ./kubernetes/deployments/core/network/nginx/internal
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: k8s-kflix
#   wait: true
#   interval: 30m
#   retryInterval: 1m
#   timeout: 5m
