# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps-arrs-overseerr
  namespace: flux-system
spec:
  targetNamespace: arrs
  commonMetadata:
    labels:
      app.kubernetes.io/name: overseerr
  path: ./kubernetes/deployments/apps/arrs/overseerr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
