apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-startup-flux-cluster-settings
  namespace: flux-system
spec:
  dependsOn:
  - name: cluster-startup-external-secrets-secret-store
  path: ./kubernetes/deployments/startup/flux-system/vars/cluster_settings
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
