apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-hajimari
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/apps/default/hajimari/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
