kube-prometheus-stack:
  nameOverride: prometheus-stack
  namespaceOverride: prometheus-stack
  alertmanager:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - alertmanager.kflix.tv
      tls:
      - hosts:
        - alertmanager.kflix.tv
        secretName: prometheus-alertmanager
  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - grafana.kflix.tv
      tls:
      - hosts:
        - grafana.kflix.tv
        secretName: prometheus-grafana
  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - prometheus.kflix.tv
      tls:
      - hosts:
        - prometheus.kflix.tv
        secretName: prometheus-prometheus