# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-startup
  namespace: flux-system
spec:
  interval: 3m
  path: ./kubernetes/deployments/startup
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  postBuild:
    substituteFrom:
    - kind: ConfigMap
      name: cluster-settings
    - kind: ConfigMap
      name: cluster-settings-user
  patches:
  - patch: |-
      apiVersion: kustomize.toolkit.fluxcd.io/v1
      kind: Kustomization
      metadata:
        name: not-used
      spec:
        postBuild:
          substituteFrom:
            - kind: ConfigMap
              name: cluster-settings
            - kind: ConfigMap
              name: cluster-settings-user
    target:
      group: kustomize.toolkit.fluxcd.io
      kind: Kustomization
      labelSelector: substitution.flux.home.arpa/disabled notin (true)
