---
- name: Reset Ceph Drives
  hosts: all
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
    - name: Pausing for 2 seconds...
      ansible.builtin.pause:
        seconds: 2
  tasks:
    - name: Reset Ceph Drives # noqa: ignore-errors
      ignore_errors: true
      block:
        - name: Delete (/var/lib/rook)
          ansible.builtin.file:
            state: absent
            path: /var/lib/rook
        - name: Delete (/dev/mapper/ceph-*) # noqa: no-changed-when
          ansible.builtin.shell: |
            set -o pipefail
            ls /dev/mapper/ceph-* | xargs -I% -- dmsetup remove_all --force % || true
        - name: Delete (/dev/ceph-*) # noqa: no-changed-when
          ansible.builtin.command: rm -rf /dev/ceph-*
        - name: Delete (/dev/mapper/ceph--*) # noqa: no-changed-when
          ansible.builtin.command: rm -rf /dev/mapper/ceph--*