- name: Server installation
  hosts:
  - master
  become: true
  gather_facts: true
  any_errors_fatal: true
  pre_tasks:
  - name: Pausing for 5 seconds...
    ansible.builtin.pause:
      seconds: 3
  tasks:
  - name: Kubeconfig
    ansible.builtin.include_tasks: tasks/wipe-disks.yaml

  - name: DevSec OS Hardening
    ansible.builtin.include_role:
      name: devsec.hardening.os_hardening
    vars:
      sysctl_overwrite:
        # Enable IPv4 traffic forwarding for k8s
        net.ipv4.ip_forward: 1
      os_always_ignore_users: [root, sync, shutdown, halt, _rpc]
  - name: DevSec SSH Hardening
    ansible.builtin.include_role:
      name: devsec.hardening.ssh_hardening
    vars:
      network_ipv6_enable: false
      ssh_allow_groups: ubuntu
  - name: ZSH Install
    ansible.builtin.include_role:
      name: manala.roles.zsh
# - name: Oh My ZSH Install
#   ansible.builtin.include_role:
#     name: manala.roles.
