# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-observability-kube-prometheus-stack
  namespace: flux-system
spec:
  dependsOn:
  - name: core-network-nginx-external
  - name: core-rook-ceph-cluster
  path: ./kubernetes/deployments/core/observability/kube-prometheus-stack/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
