# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/minio.min.io/tenant_v2.json
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio
  namespace: minio-tenant
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
spec:
  features:
    bucketDNS: true
  ## Create users in the Tenant using this field. Make sure to create secrets per user added here.
  ## Secret should follow the format used in `minio-creds-secret`.
  users:
  - name: storage-user
  ## Create buckets using the console user
  # buckets:
  #   - name: "test-bucket1"
  #     region: "us-east-1"
  #     objectLock: true
  #   - name: "test-bucket2"
  #     region: "us-east-1"
  #     objectLock: true

  ## Secret with credentials and configurations to be used by MinIO Tenant.
  configuration:
    name: storage-configuration
  ## Add environment variables to be set in MinIO container (https://github.com/minio/minio/tree/master/docs/config)
  env:
  - name: MINIO_DOMAIN
    value: "minio.${SECRET_DOMAIN}"
  - name: MINIO_BROWSER_REDIRECT_URL
    value: "https://console.${SECRET_DOMAIN}"
  - name: MINIO_SERVER_URL
    value: "https://minio.${SECRET_DOMAIN}"

  ## Registry location and Tag to download MinIO Server image
  image: quay.io/minio/minio:RELEASE.2023-09-07T02-05-02Z

  ## Specification for MinIO Pool(s) in this Tenant.
  pools:
  - servers: 4
    name: pool-0
    volumesPerServer: 4
    volumeClaimTemplate:
      apiVersion: v1
      kind: persistentvolumeclaims
      metadata: {}
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 3Gi
        storageClassName: longhorn-kflix
  ## Enable automatic Kubernetes based certificate generation and signing as explained in
  ## https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster
  requestAutoCert: false
