# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-database-cloudnative-pg
  namespace: flux-system
spec:
  dependsOn:
  - name: core-rook-ceph-cluster
  path: ./kubernetes/deployments/core/database/cloudnative-pg/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-database-cloudnative-pg-cluster
  namespace: flux-system
spec:
  dependsOn:
  - name: core-database-cloudnative-pg
  path: ./kubernetes/deployments/core/database/cloudnative-pg/cluster
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
