# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-tfrc
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "terraform.tfrc"
      property: "terraform.tfrc"
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-cloud
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: terraform-cloud
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        tfe_organization: "{{ .tfe_organization }}"
        tfe_token: "{{ .tfe_token }}"
        tfe_project: "{{ .tfe_project }}"
        cloudflare_api_token: "{{ .cloudflare_api_token }}"
  dataFrom:
  - extract:
      key: "terraform cloud"
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-cloudflare
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: terraform-cloudflare
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        cloudflare_domain: "{{ .cloudflare_domain }}"
  dataFrom:
  - extract:
      key: "Cloudflare"
