# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: terraform-cloud
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: terraform-cloud
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "terraform cloud"
