apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: jenkins-admin
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store # Must match SecretStore on the cluster

  target:
    name: jenkins-admin # Name for the secret to be created on the cluster
    creationPolicy: Owner

  data:
  - secretKey: jenkins-admin-password
    remoteRef:
      key: jenkins-admin-password