# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./remove-cpu-limits.yaml
- ./add-default-resources.yaml
# - ./add-imagepull-secrets.yaml # TODO: Add this after clustersecrets is setup
- ./disallow-empty-ingress-host.yaml
- ./disallow-latest-tag.yaml
