# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: kubernetes-cloudflare
  namespace: flux-system
spec:
  suspend: false
  approvePlan: auto
  interval: 12h
  path: ./kubernetes/tfcloud
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  varsFrom:
  - kind: Secret
    name: terraform-cloud
