# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/infra.contrib.fluxcd.io/terraform_v1alpha2.json
apiVersion: infra.contrib.fluxcd.io/v1alpha2
kind: Terraform
metadata:
  name: tfcloud
  namespace: flux-system
spec:
  suspend: false
  approvePlan: auto
  interval: 12h
  path: ./kubernetes/tf-cloud
  sourceRef:
    kind: OCIRepository
    name: terraform
    namespace: flux-system
  varsFrom:
  - kind: Secret
    name: terraform-cloud
    varsKeys:
    - tfe_token
    - tfe_organization
    - tfe_project
  - kind: ConfigMap
    name: tf-controller-bucket
    varsKeys:
    - BUCKET_NAME
    - BUCKET_HOST
  - kind: Secret
    name: tf-controller-bucket
    varsKeys:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
