apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-core-cloudflare-zerotrust
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/core/zero-trust/cloudflare-zerotrust/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  interval: 30m
  retryInterval: 1m
  timeout: 5m
