# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-zero-trust-cloudflare-zerotrust
  namespace: flux-system
spec:
  dependsOn:
  - name: core-network-cloudflared
  path: ./kubernetes/deployments/core/zero-trust/cloudflare-zerotrust/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  interval: 30m
  retryInterval: 1m
  timeout: 5m
# yamllint disable-line rule:document-start
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-zero-trust-access-group
  namespace: flux-system
spec:
  dependsOn:
  - name: core-zero-trust-cloudflare-zerotrust
  path: ./kubernetes/deployments/core/zero-trust/cloudflare-zerotrust/access-group
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  interval: 30m
  retryInterval: 1m
  timeout: 5m
