# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/clustersecret.io/clustersecret_v1.json
apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: ghcr-credentials
  namespace: clustersecret
avoidNamespaces:
- external-secrets
data:
  valueFrom:
    secretKeyRef:
      name: ghcr-credentials
      namespace: external-secrets
