apiVersion: clustersecret.io/v1
kind: ClusterSecret
metadata:
  name: ghcr-credentials
  namespace: clustersecret
avoidNamespaces:
- external-secrets
data:
  valueFrom:
    secretKeyRef:
      name: ghcr-credentials
      namespace: external-secrets
