# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rclone-secret
  namespace: storage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: "rclone config"
      property: configData
  data:
  - secretKey: remote
    remoteRef:
      key: "Rclone"
      property: "remote"
  - secretKey: remotePath
    remoteRef:
      key: "Rclone"
      property: "remotePath"
