# yaml-language-server: $schema=https://k8s-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: rclone-mount
  namespace: storage
spec:
  interval: 5m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # Helm postrenderer that adds mountPropagation: Bidirectional to the rclone-mount container
  postRenderers:
  - kustomize:
      patchesStrategicMerge:
      - ./patches/mount-propagation-patch.yaml
  values:
    controllers:
      main:
        replicas: 1
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-config:
            image:
              repository: docker.io/mumiehub/rclone-mount
              tag: v1.65.0
            command: ["/bin/sh", "-c"]
            args: ["cp /tmp/secret/* /config/"]
        containers:
          main:
            image:
              repository: docker.io/mumiehub/rclone-mount
              tag: v1.65.0
              pullPolicy: IfNotPresent
            env:
              ConfigName: "rclone.conf"
              TZ: America/New_York # TODO: Move TZ to cluster-settings
              RemotePath: "encrypt:"
              MountPoint: "/mnt/rclone"
              MountCommands: >-
                --allow-other --allow-non-empty --dir-cache-time 24h --umask 002 --log-level DEBUG
            securityContext:
              privileged: true
              readOnlyRootFilesystem: false
              fsGroupChangePolicy: OnRootMismatch
              capabilities:
                add:
                - SYS_ADMIN
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
                smarter-devices/fuse: 1
              limits:
                cpu: 300m
                memory: 5Gi
                smarter-devices/fuse: 1
          mergerfs:
            image:
              repository: ghcr.io/hotio/mergerfs
              tag: release-2.37.1
              pullPolicy: IfNotPresent
            args: ["-o", "allow_other", "/mnt/rclone=RO:/mnt/local-cache", "/mnt/mergerfs"]
            env:
              TZ: America/New_York # TODO: Move TZ to cluster-settings
            securityContext:
              privileged: true
              readOnlyRootFilesystem: false
              fsGroupChangePolicy: OnRootMismatch
              capabilities:
                add:
                - SYS_ADMIN
            resources:
              requests:
                cpu: 100m
                memory: 1Gi
                smarter-devices/fuse: 1
              limits:
                cpu: 300m
                memory: 5Gi
                smarter-devices/fuse: 1
    service:
      main:
        enabled: false
    persistence:
      config:
        enabled: true
        type: emptyDir
        globalMounts:
        - path: /config
      rclone-secret:
        enabled: true
        type: secret
        name: rclone-secret
        advancedMounts:
          main:
            init-config:
            - path: /tmp/secret/rclone.conf
              subPath: configData
      rclone-mount:
        enabled: true
        existingClaim: rclone-pvc
        globalMounts:
        - path: /mnt/rclone
      local-cache:
        enabled: true
        existingClaim: local-cache-pvc
        globalMounts:
        - path: /mnt/local-cache
      mergerfs:
        enabled: true
        existingClaim: mergerfs-pvc
        globalMounts:
        - path: /mnt/mergerfs
