# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage
resources:
- ./externalsecret.yaml
- ./rclone-pvc.yaml
- ./mergerfs-pvc.yaml
- ./local-cache-pvc.yaml
- ./helmrelease.yaml
