github_username: kiliantyler
timezone: America/New_York
coredns_addr: "10.43.0.10"
kube_vip_addr: "167.114.212.248"
cluster_cidr: "10.42.0.0/16"
service_cidr: "10.43.0.0/16"
node_cidr: "167.114.212.248/29"
