# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clustersecret
resources:
# - ./helmrelease.yaml # TODO: Change back to helm once it gets updated
- ./00_rbac.yaml
- ./01_crd.yaml
- ./02_deployment.yaml
