prowlarr:
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/tls-acme: "true"
      hosts:
      - host: prowlarr.kflix.tv
        paths:
        - path: /
          pathType: Prefix
      tls:
        - secretName: prowlarr-tls.local
          hosts:
            - prowlarr.kflix.tv
  persistence:
    config:
      enabled: true
      existingClaim: prowlarr-longhorn-pvc
