---
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 2.11.0
  - name: community.general
    version: 7.4.0
  - name: community.sops
    version: 1.6.6
  - name: kubernetes.core
    version: 2.4.0
  - name: onepassword.connect
    version: 2.2.3
  - name: devsec.hardening
    version: 8.8.0
  - name: manala.roles
    version: 3.7.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  # - name: budimanjojo.duo_ssh
  # - name: andbanman.duo_unix
  # - name: kflixtv.duo_unix
  #   src: https://github.com/kFlix-tv/ansible-role-duo-unix