---
collections:
  - name: community.general
    version: 7.2.1
  - name: community.sops
    version: 1.6.4
  - name: ansible.posix
    version: 1.5.2
  - name: ansible.utils
    version: 2.10.3
  - name: kubernetes.core
    version: 2.4.0
roles:
  - name: xanmanning.k3s
    src: https://github.com/PyratLabs/ansible-role-k3s.git
    version: v3.4.2
  - name: budimanjojo.duo_ssh
  - name: andbanman.duo_unix
  - name: kflixtv.duo_unix
    src: https://github.com/kFlix-tv/ansible-role-duo-unix