# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kube-system-snapshot-controller
  namespace: flux-system
spec:
  # TODO: This might need to depend on Rook-Ceph, or vice versa
  path: ./kubernetes/deployments/core/kube-system/snapshot-controller/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
