# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-observability-gatus
  namespace: flux-system
spec:
  dependsOn:
  - name: core-database-cloudnative-pg-cluster
  path: ./kubernetes/deployments/core/observability/gatus/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
