# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/ceph.rook.io/cephcluster_v1.json
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  cephVersion:
    image: quay.io/ceph/ceph:v18.2.0
  dataDirHostPath: /var/lib/rook
  dashboard:
    enabled: true
    urlPrefix: /
    ssl: false
  crashCollector:
    disable: false
  network:
    provider: host
    connections:
      compression:
        enabled: true
      requireMsgr2: true
  mon:
    count: 3
    allowMultiplePerNode: true
  storage:
    useAllNodes: true
    useAllDevices: true
