apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.metadata.project }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'