# yaml-language-server builtin
apiVersion: v1
kind: ConfigMap
metadata:
  name: echo-server-gatus-ep
  namespace: networking
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: echo-server
        group: External
        url: https://echo-server.kflix.tv
        interval: 1m
        client:
          dns-resolver: tcp://1.1.1.1:53
        conditions:
          - "[STATUS] == 200"
