apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-longhorn-pvc
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-kflix
  resources:
    requests:
      storage: 2Gi
  volumeName: prowlarr-longhorn-pv