apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-longhorn
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-kflix
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: prowlarr-longhorn