apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-longhorn-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-4"
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-kflix
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: '1'
      staleReplicaTimeout: '2880'
    volumeHandle: prowlarr-longhorn