apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: prowlarr-longhorn
  storageClassName: longhorn-kflix