apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prowlarr-longhorn-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-kflix
  resources:
    requests:
      storage: 2Gi
  volumeName: prowlarr-longhorn