# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-kube-system-reloader
  namespace: flux-system
spec:
  dependsOn:
  - name: core-rook-ceph-cluster
  - name: core-flux-system-webhooks
  - name: core-observability-kubernetes-dashboard
  - name: core-flux-system-weave-gitops
  - name: core-observability-kube-prometheus-stack
  - name: core-observability-grafana
  - name: core-network-echo-server
  path: ./kubernetes/deployments/core/kube-system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
