# yaml-language-server: $schema=https://kubernetes-schemas.kflix.tv/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: core-reloader
  namespace: flux-system
spec:
  dependsOn:
  - name: core-longhorn-settings
  - name: core-flux-webhooks
  - name: core-kubernetes-dashboard
  - name: core-weave-gitops
  - name: core-kube-prometheus-stack
  - name: core-grafana
  - name: core-echo-server
  path: ./kubernetes/deployments/core/kube-system/reloader/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: false
  interval: 30m
  retryInterval: 1m
  timeout: 5m
