---
- name: Copy kubeconfig to the project directory
  when: k3s_primary_control_node
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: /Users/kilian/.kube/config-files/kflix.yaml
    flat: true

- name: Update kubeconfig with the correct load balancer address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: /Users/kilian/.kube/config-files/kflix.yaml
    regexp: https://127.0.0.1:6443
    replace: "https://{{ k3s_registration_address }}:6443"
