---
- name: Copy kubeconfig to the project directory
  ansible.builtin.fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ lookup('env', 'HOME') }}/.kube/config-files/kflix.yaml"
    flat: true

- name: Update kubeconfig with the correct load balancer address
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config-files/kflix.yaml"
    regexp: https://127.0.0.1:6443
    replace: "https://{{ k3s_registration_address }}:6443"

- name: Update kubeconfig cluster
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config-files/kflix.yaml"
    regexp: 'cluster: default'
    replace: 'cluster: kflix'

- name: Update kubeconfig context name
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config-files/kflix.yaml"
    regexp: 'name: default'
    replace: 'name: kflix'

- name: Update kubeconfig user name
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config-files/kflix.yaml"
    regexp: 'user: default'
    replace: 'user: kflix'

- name: Update kubeconfig current-context
  delegate_to: localhost
  become: false
  run_once: true
  ansible.builtin.replace:
    path: "{{ lookup('env', 'HOME') }}/.kube/config-files/kflix.yaml"
    regexp: 'current-context: default'
    replace: 'current-context: kflix'