apiVersion: v2
name: jenkins
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.0"

dependencies:
- name: jenkins
  version: ~11.0.9
  repository: https://charts.bitnami.com/bitnami