uptime-kuma:
  env:
    TZ: "America/Los_Angeles"
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
      - host: uptime.kflix.tv
        paths:
        - path: /
          pathType: Prefix
      tls:
      - hosts:
        - uptime.{{ .Values.server.urlbase }}