uptime-kuma:
  env:
    TZ: "America/Los_Angeles"
  ingress:
    main:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        cert-manager.io/cluster-issuer: letsencrypt
        external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
      hosts:
      - host: uptime.kflix.tv
        paths:
        - path: /
          pathType: Prefix
      - host: status.kflix.tv
        paths:
        - path: /status
          pathType: Prefix
      tls:
      - secretName: uptime-kuma-tls
        hosts:
        - uptime.kflix.tv
      - secretName: uptime-kuma-status-tls
        hosts:
        - status.kflix.tv