name: Broken Link Check

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"

jobs:
  check-links:
    name: Check Links
    permissions:
      contents: read
      issues: write
    runs-on: ["arc-runner-set-kflix"]
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: Scan for broken links
      uses: lycheeverse/lychee-action@c3089c702fbb949e3f7a8122be0c33c017904f9b # v1.9.1
      id: lychee
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: --verbose --no-progress --exclude-mail './**/*.md'

    - name: Find Link Checker Issue
      id: broken-link-check-issue
      uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2.3.0
      with:
        state: open
        labels: broken-links

    - name: Update Issue
      uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # v4.0.1
      with:
        title: Broken links detected 🔗
        issue-number: ${{ steps.broken-link-check-issue.outputs.issue-number }}
        content-filepath: ./lychee/out.md
        token: ${{ secrets.GITHUB_TOKEN }}
        labels: broken-links
