# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Kubeconform"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

env:
  KUBERNETES_DIR: ./kubernetes

jobs:
  kubeconform:
    name: Kubeconform
    permissions:
      contents: read
      pull-requests: write
    runs-on: ["arc-runner-set-kflix"]
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup Workflow Tools
      run: brew install fluxcd/tap/flux kubeconform kustomize

    - name: Run kubeconform
      shell: bash
      run: ./.github/scripts/kubeconform.sh ${{ env.KUBERNETES_DIR }}
