# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Kubeconform"

on:
  pull_request:
    branches: ["main"]
    paths: ["kubernetes/**"]

env:
  KUBERNETES_DIR: ./kubernetes
  WORKFLOW_RESOURCE_DIR: ./.github/workflows/resources

jobs:
  kubeconform:
    name: Kubeconform
    permissions:
      contents: read
      pull-requests: write
    runs-on: ["arc-runner-set-kflix"]
    steps:
    - name: Checkout
      uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

    - name: Setup Homebrew
      uses: Homebrew/actions/setup-homebrew@master

    - name: Setup Workflow Tools
      run: brew install fluxcd/tap/flux kubeconform kustomize

    - name: Run kubeconform
      shell: bash
      run: ${{ env.WORKFLOW_RESOURCE_DIR }}/kubeconform.sh ${{ env.KUBERNETES_DIR }}
