# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Publish Schemas"

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * 0"
  push:
    branches: ["main"]
    paths: [".github/workflows/publish-schemas.yaml"]

env:
  DEBCONF_NONINTERACTIVE_SEEN: "true"
  DEBIAN_FRONTEND: noninteractive
  APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE: DontWarn
  WORKFLOW_RESOURCE_DIR: ./.github/workflows/resources
  SCHEMAS_DIR: /home/runner/crds

jobs:
  publish-schemas:
    name: Publish Schemas
    runs-on: ["arc-runner-set-kflix"]
    permissions:
      contents: read
      packages: write
    steps:

    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Install OS Deps
      shell: bash
      run: sudo apt-get update && sudo apt-get install -y curl git xz-utils

    - name: Install Nix
      uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7 # v24
      with:
        github_access_token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Switch to Nix devShell
      uses: nicknovitski/nix-develop@a2060d116a50b36dfab02280af558e73ab52427d # v1.1.0
      with:
        arguments: "${{ env.WORKFLOW_RESOURCE_DIR }}"

    - name: Setup Node
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
      with:
        node-version: 18.x

    - name: Setup Python
      uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
      with:
        python-version: 3.x

    - name: Write kubeconfig
      id: kubeconfig
      uses: timheuer/base64-to-file@784a1a4a994315802b7d8e2084e116e783d157be # v1.2.4
      with:
        encodedString: "${{ secrets.KUBECONFIG }}"
        fileName: kubeconfig

    - name: Download and run crd-extractor
      env:
        KUBECONFIG: "${{ steps.kubeconfig.outputs.filePath }}"
      shell: bash
      run: |
        mkdir -p ${{ env.SCHEMAS_DIR }}
        curl -fsSL -o $GITHUB_WORKSPACE/crd-extractor.sh \
            https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/Utilities/crd-extractor.sh
        chmod +x $GITHUB_WORKSPACE/crd-extractor.sh
        bash $GITHUB_WORKSPACE/crd-extractor.sh
        mv /home/runner/.datree/crdSchemas/* ${{ env.SCHEMAS_DIR }}

    - name: Deploy to Cloudflare Pages
      uses: cloudflare/wrangler-action@a8be0ea72a399752dd2735fa16ea0d424f2335ca # v3.4.0
      with:
        apiToken: "${{ secrets.CLOUDFLARE_API_TOKEN }}"
        accountId: "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
        workingDirectory: "${{ env.SCHEMAS_DIR }}"
        command: pages deploy --project-name=k8s-schemas --branch main .
