name: "Publish Terraform"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: ["terraform/**"]

jobs:
  publish-terraform:
    name: Publish Terraform
    runs-on: ["arc-runner-set-kflix"]
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Setup Flux
      uses: fluxcd/flux2/action@534684601ec8888beb0cc4f51117b59e97606c4d # v2.2.3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
      with:
        registry: ghcr.io
        username: "${{ github.actor }}"
        password: "${{ secrets.GITHUB_TOKEN }}"

    - name: Repo owner to lowercase
      id: repo_owner
      shell: bash
      run: echo "repo-owner=$(echo ${GITHUB_REPOSITORY_OWNER} | tr '[:upper:]' '[:lower:]')" >> "${GITHUB_OUTPUT}"

    - name: Generate tag
      id: generate-tag
      shell: bash
      run: echo "tag=ghcr.io/${{ steps.repo_owner.outputs.repo-owner }}/manifests/terraform:$(git rev-parse --short HEAD)" >> "${GITHUB_OUTPUT}"

    - name: Publish manifests
      shell: bash
      run: |
        flux push artifact oci://${{ steps.generate-tag.outputs.tag }} \
            --path="./terraform" \
            --source="$(git config --get remote.origin.url)" \
            --revision="$(git branch --show-current)/$(git rev-parse HEAD)"

    - name: Tag manifests
      shell: bash
      run: flux tag artifact oci://${{ steps.generate-tag.outputs.tag }} --tag main
